### ISSUE TITLE
how to support prefix search in cpp-fstlib?

### ISSUE THREAD

**Issue by ChasenYang** [yhirose/cpp-fstlib#10]
I use API named `common_prefix_search` but the result is not what i want.
I use the example in tutorials.
for example:

```
// input
const std::vector<std::pair<std::string, std::string>> items = {
  {"hello", "こんにちは!"},
  {"hello world", "こんにちは世界!"}, // incorrect sort order entry...
  {"world", "世界!"},
};
//Omit the initialization process for fstmap; 
//....

//search result with prefix 'h' but no result returned.
auto prefixes = matcher.common_prefix_search("h");

//output=0;
cout << prefixes.size() << endl;  
```
I expect the result to be “こんにちは!” and “こんにちは世界!”.
Which interface can get the expected result? And what does 'common_prefix_search' mean?

**Comment by yhirose** [comment]
@ChasenYang, thanks for the feedback. This library doesn't support 'prefix' search that you are trying to do. What `common_prefix_search` does is to iterate all the words in a fst database and return a list of 'common prefix' of each word.

You can find more information by googling with 'common prefix' or 'longest common prefix'.
Hope it helps!
