### ISSUE TITLE
how to dynamically add new items after fst::compile called ?

### ISSUE THREAD

**Issue by 454036792** [yhirose/cpp-fstlib#11]
const std::vector<std::pair<std::string, std::string>> items = 
  {
       {"hello", "a"},
       {"hello world", "b"},
       {"world", "c"}
  };

  std::stringstream out;
  auto sorted = false; // ask fst::compile to sort entries
  auto [result, error_line] = fst::compile<std::string>(items, out, sorted);

   const auto &byte_code = out.str();
   fst::map<std::string> matcher(byte_code.data(), byte_code.size());

  //do something
  ****** here, I have more items to add, how to do that ?  ******

**Comment by yhirose** [comment]
@454036792, this library doesn't support such a dynamic construction. Sorry...
