### ISSUE TITLE
is it possible to use mmap lazy initilize for search to reduce memory usage？

### ISSUE THREAD

**Issue by mtxrym** [yhirose/cpp-fstlib#9]
when too many terms（billions of），memory usage is huge（servel GB）； Lucene  uses pagecache to lazy load fst bytes，is it possible for fstlib？

**Comment by yhirose** [comment]
@mtxrym, yes it actually supports already. machters (map and set) just takes a byte pointer and buffer length. So you can open the compiled fst binary database with mmap and pass it to a macher.

```cpp
  map(const char *byte_code, size_t byte_code_size)
```

Hope it helps!
